# CISSP 2024 8个域的元数据定义

DOMAINS = {
    1: {
        "name": "安全与风险管理",
        "name_en": "Security and Risk Management",
        "weight": 0.16,
        "exam_questions": 20,
        "subdomains": [
            "职业道德",
            "安全概念（CIA三元组）",
            "安全治理原则",
            "合规要求",
            "法律法规与隐私",
            "IT政策与标准",
            "业务连续性要求",
            "人员安全政策",
            "风险管理概念",
            "威胁建模",
            "供应链风险管理",
            "安全意识与培训",
        ],
        "key_concepts": [
            "CIA（保密性/完整性/可用性）",
            "SLE = AV × EF | ALE = SLE × ARO",
            "定性风险 vs 定量风险分析",
            "ISC2职业道德准则（4条）",
            "NIST/ISO 27001/COBIT框架",
            "BCP/DRP区别",
        ],
    },
    2: {
        "name": "资产安全",
        "name_en": "Asset Security",
        "weight": 0.10,
        "exam_questions": 13,
        "subdomains": [
            "资产识别与分类",
            "数据所有权角色",
            "保护隐私",
            "数据保留策略",
            "数据安全控制",
            "数据处理要求",
        ],
        "key_concepts": [
            "数据分类级别（绝密/机密/秘密/公开）",
            "数据所有者/保管者/处理者/用户角色",
            "数据状态：静态/传输中/使用中",
            "数据销毁方法（清除/清洗/销毁）",
            "DLP/DRM/CASB数据保护工具",
        ],
    },
    3: {
        "name": "安全架构与工程",
        "name_en": "Security Architecture and Engineering",
        "weight": 0.13,
        "exam_questions": 16,
        "subdomains": [
            "安全设计原则",
            "安全模型",
            "评估和选择控制",
            "信息系统安全能力",
            "评估和缓解漏洞",
            "密码学原理",
            "密码攻击与方法",
            "站点和设施安全设计",
            "物理安全",
            "云与分布式计算安全",
        ],
        "key_concepts": [
            "最小权限/职责分离/深度防御/零信任",
            "Bell-LaPadula（保密性）/Biba（完整性）模型",
            "对称加密（AES）vs 非对称加密（RSA/ECC）",
            "哈希算法（SHA-256/MD5已弃用）",
            "PKI/数字证书/CA信任链",
            "STRIDE威胁建模",
        ],
    },
    4: {
        "name": "通信与网络安全",
        "name_en": "Communication and Network Security",
        "weight": 0.13,
        "exam_questions": 16,
        "subdomains": [
            "网络架构安全设计",
            "网络组件安全",
            "安全通信渠道",
        ],
        "key_concepts": [
            "OSI 7层模型 vs TCP/IP 4层模型",
            "VPN协议（IPsec/L2TP/SSL-VPN）",
            "防火墙类型（包过滤/状态检测/应用层）",
            "DNS/DHCP/BGP安全",
            "无线安全（WPA3/802.1X）",
            "DKIM/SPF/DMARC邮件安全",
        ],
    },
    5: {
        "name": "身份与访问管理",
        "name_en": "Identity and Access Management",
        "weight": 0.13,
        "exam_questions": 16,
        "subdomains": [
            "物理和逻辑资产访问控制",
            "身份和访问配置管理",
            "身份验证机制",
            "联合身份与单点登录",
            "授权机制",
            "身份和访问攻击防护",
        ],
        "key_concepts": [
            "AAA（认证/授权/审计）",
            "三因素认证（知识/所有权/生物特征）",
            "RBAC/MAC/DAC/ABAC访问控制模型",
            "Kerberos/RADIUS/TACACS+",
            "OAuth 2.0/SAML/OpenID Connect",
            "生物特征：FAR/FRR/CER",
        ],
    },
    6: {
        "name": "安全评估与测试",
        "name_en": "Security Assessment and Testing",
        "weight": 0.12,
        "exam_questions": 15,
        "subdomains": [
            "评估和测试策略设计",
            "安全控制测试",
            "收集安全流程数据",
            "分析测试输出和报告",
            "内外部审计",
        ],
        "key_concepts": [
            "渗透测试（黑盒/灰盒/白盒）",
            "红队/蓝队/紫队",
            "漏洞扫描 vs 渗透测试",
            "SOC 1/2/3报告（SSAE 18）",
            "SAST/DAST/IAST代码测试",
            "KPI/KRI安全度量指标",
        ],
    },
    7: {
        "name": "安全运营",
        "name_en": "Security Operations",
        "weight": 0.13,
        "exam_questions": 16,
        "subdomains": [
            "调查类型与支持",
            "日志记录与监控",
            "资产安全配置管理",
            "漏洞与补丁管理",
            "变更管理流程",
            "事件响应",
            "数字取证",
            "灾难恢复",
            "业务连续性计划",
            "物理安全运营",
            "人员安全",
            "供应链安全",
            "安全意识培训",
            "网络流量分析",
            "安全服务水平协议",
        ],
        "key_concepts": [
            "事件响应6步骤（准备/识别/遏制/根除/恢复/经验总结）",
            "取证证据链（CoC）",
            "SIEM/SOC/NOC",
            "RTO/RPO/MTD/MTBF/MTTR",
            "全备份/增量备份/差异备份",
        ],
    },
    8: {
        "name": "软件开发安全",
        "name_en": "Software Development Security",
        "weight": 0.10,
        "exam_questions": 13,
        "subdomains": [
            "安全软件开发生命周期（SDLC）",
            "开发环境安全控制",
            "软件安全效能评估",
            "评估供应商和第三方安全",
            "应用安全测试",
        ],
        "key_concepts": [
            "SDLC各阶段安全活动",
            "DevSecOps与安全左移",
            "OWASP Top 10漏洞",
            "输入验证/参数化查询（防SQL注入）",
            "缓冲区溢出/TOCTOU竞态条件",
            "代码审查/SAST静态分析",
        ],
    },
}

DOMAIN_IDS = list(DOMAINS.keys())

def get_domain(domain_id: int) -> dict:
    return DOMAINS.get(domain_id, {})

def get_all_domains() -> list[dict]:
    return [{"id": k, **v} for k, v in DOMAINS.items()]
